package com.rfsat.tinyrad.data.repository

import android.content.Context
import com.rfsat.tinyrad.data.models.DetectedObject
import com.rfsat.tinyrad.data.models.RadarFrame
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileWriter
import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

private val ISO = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    .withZone(ZoneOffset.UTC)

class RecordingRepository(private val context: Context) {

    private var writer:      FileWriter? = null
    private var currentFile: File?       = null
    private var rowCount:    Int         = 0

    /** Returns the path of the newly opened CSV file. */
    suspend fun startRecording(sessionTag: String = ""): String = withContext(Dispatchers.IO) {
        val dir  = File(context.getExternalFilesDir(null), "TinyRAD").also { it.mkdirs() }
        val ts   = ISO.format(Instant.now()).replace(":", "-").replace(".", "-")
        val tag  = if (sessionTag.isNotBlank()) "_${sessionTag}" else ""
        val file = File(dir, "TinyRAD${tag}_$ts.csv")

        writer = FileWriter(file, false)
        currentFile = file
        rowCount    = 0

        // Metadata header
        writer!!.write("# RFSAT Limited — ENACT Project (Horizon Europe Grant 101157101)\n")
        writer!!.write("# TinyRAD FMCW Radar Recording\n")
        writer!!.write("# Session start: ${ISO.format(Instant.now())}\n")
        writer!!.write("# Generated by TinyRadApp v1.0\n")
        // Column header
        writer!!.write("timestamp_iso,timestamp_ms,frame_index,track_id,object_class," +
                "distance_m,azimuth_deg,elevation_deg,speed_mps,speed_kmh," +
                "direction,snr_db,confidence\n")
        writer!!.flush()
        file.absolutePath
    }

    suspend fun writeFrame(frame: RadarFrame) = withContext(Dispatchers.IO) {
        val w = writer ?: return@withContext
        val ts = ISO.format(Instant.ofEpochMilli(frame.timestampMs))

        if (frame.detectedObjects.isEmpty()) {
            // Write one empty row so the timeline is continuous
            w.write("$ts,${frame.timestampMs},${frame.frameIndex},,,,,,,,,,\n")
            rowCount++
        } else {
            for (obj in frame.detectedObjects) {
                w.write(buildRow(ts, frame.timestampMs, frame.frameIndex, obj))
                rowCount++
            }
        }
        if (rowCount % 50 == 0) w.flush()
    }

    private fun buildRow(ts: String, tsMs: Long, fi: Long, o: DetectedObject) =
        "$ts,$tsMs,$fi,${o.trackId},${o.objectClass.displayName}," +
        "${"%.2f".format(o.distanceM)},${"%.1f".format(o.azimuthDeg)}," +
        "${"%.1f".format(o.elevationDeg)},${"%.3f".format(o.speedMps)}," +
        "${"%.2f".format(o.speedKmh)},${o.direction.displayName}," +
        "${"%.1f".format(o.snrDb)},${"%.2f".format(o.confidence)}\n"

    suspend fun stopRecording(): String? = withContext(Dispatchers.IO) {
        writer?.flush()
        writer?.close()
        writer = null
        currentFile?.absolutePath.also { currentFile = null; rowCount = 0 }
    }

    fun currentPath(): String?  = currentFile?.absolutePath
    fun currentRows(): Int      = rowCount

    /** List all previously recorded CSV files, newest first. */
    fun listRecordings(): List<File> {
        val dir = File(context.getExternalFilesDir(null), "TinyRAD")
        return dir.listFiles { f -> f.extension == "csv" }
            ?.sortedByDescending { it.lastModified() }
            ?: emptyList()
    }
}
